kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs4-v1
  namespace: demo
  labels:
    app: nodejs4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs4
      version: v1
  template:
    metadata:
      labels:
        app: nodejs4
    spec:
      containers:
        - name: container-95uqzn
          image: $REGISTRY/$HARBOR_PROJECT/$APP_NAME:SNAPSHOT-$BUILD_NUMBER
          ports:
            - name: http-port
              containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      imagePullSecrets:
        - name: harbor-id
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600