apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-dev
  namespace: demo
  labels:
    app: nodejs-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-dev
  template:
    metadata:
      labels:
        app: nodejs-dev
    spec:
      containers:
      - name: nodejs-dev
        image: $REGISTRY/$HARBOR_PROJECT/$APP_NAME:SNAPSHOT-$BUILD_NUMBER
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
      imagePullSecrets:
      - name: harbor-id
      dnsPolicy: ClusterFirstWithHostNet